export const orderList = [
  {
    orderId: "#CM9081",
    userName: "Natali Craig",
    userImage: "Female15.png",
    projectName: "Landing Page",
    address: "Meadow Lane Oakland",
    date: "Just now",
    status: "IN_PROGRESS",
    status_text: "In Progress",
    status_color: "#8a8cd9",
  },
  {
    orderId: "#CM9082",
    userName: "Kate Morrison",
    userImage: "Female09.png",
    projectName: "CRM Admin Pages",
    address: "Larry San Francisco",
    date: "A minute ago",
    status: "COMPLETE",
    status_text: "Complete",
    status_color: "#4aa785",
  },
  {
    orderId: "#CM9083",
    userName: "Drew Cano",
    userImage: "Male08.png",
    projectName: "Client Project",
    address: "Bagwell Avenue Ocala",
    date: "1 hour ago",
    status: "PENDING",
    status_text: "Pending",
    status_color: "#59a8d4",
  },
  {
    orderId: "#CM9084",
    userName: "Orlando Diggs",
    userImage: "Male06.png",
    projectName: "Admin Dashboard",
    address: "Washburn Baton Rouge",
    date: "Yesterday",
    status: "APPROVED",
    status_text: "Approved",
    status_color: "#ffc555",
  },
  {
    orderId: "#CM9085",
    userName: "Andie Lane",
    userImage: "Female08.png",
    projectName: "App Landing Page",
    address: "Nest Lane Olivette",
    date: "Feb 2, 2023",
    status: "REJECTED",
    status_text: "Rejected",
    status_color: "#1c1c1c",
    dark_status_color: "rgba(255, 255, 255, 0.4)",
  },
  {
    orderId: "#CM9081",
    userName: "Natali Craig",
    userImage: "Female15.png",
    projectName: "Landing Page",
    address: "Meadow Lane Oakland",
    date: "Just now",
    status: "IN_PROGRESS",
    status_text: "In Progress",
    status_color: "#8a8cd9",
  },
  {
    orderId: "#CM9082",
    userName: "Kate Morrison",
    userImage: "Female09.png",
    projectName: "CRM Admin Pages",
    address: "Larry San Francisco",
    date: "A minute ago",
    status: "COMPLETE",
    status_text: "Complete",
    status_color: "#4aa785",
  },
  {
    orderId: "#CM9083",
    userName: "Drew Cano",
    userImage: "Male08.png",
    projectName: "Client Project",
    address: "Bagwell Avenue Ocala",
    date: "1 hour ago",
    status: "PENDING",
    status_text: "Pending",
    status_color: "#59a8d4",
  },
  {
    orderId: "#CM9084",
    userName: "Orlando Diggs",
    userImage: "Male06.png",
    projectName: "Admin Dashboard",
    address: "Washburn Baton Rouge",
    date: "Yesterday",
    status: "APPROVED",
    status_text: "Approved",
    status_color: "#ffc555",
  },
  {
    orderId: "#CM9085",
    userName: "Andie Lane",
    userImage: "Female08.png",
    projectName: "App Landing Page",
    address: "Nest Lane Olivette",
    date: "Feb 2, 2023",
    status: "REJECTED",
    status_text: "Rejected",
    status_color: "#1c1c1c",
    dark_status_color: "rgba(255, 255, 255, 0.4)",
  },
];